In [6]:
#1)Python program to find the number with longest length.
a = []
n = int(input("Enter the no. of elements in list: "))
for x in range(0,n):
    element=input("Enter element")
    a.append(element)
max1 = len(a[0])
temp = a[0]
for i in a:
    if(len(i) > max1):  
        max1 = len(i)
        temp = i
print("The word with the longest length is: ")
print(temp)

Enter the no. of elements in list: 3
Enter element12
Enter element456
Enter element900000
The word with the longest length is: 
900000


In [7]:
#2)Python program to draw the pattern
n=7
for i in range(0,n):
    print('*'*i)
    if i==(n-1):
        for i in range(n,0,-1):
            print('*'*i)


*
**
***
****
*****
******
*******
******
*****
****
***
**
*


In [16]:
#3)Python program to print each element and find its type from a list

L = [1234, 33.33, 1+2j, 'priti', True,(0,-1),[5,12],{'class':'v','grade':'a'}]

for i in L:
     print(i, ':',type(i))
        

1234 : <class 'int'>
33.33 : <class 'float'>
(1+2j) : <class 'complex'>
priti : <class 'str'>
True : <class 'bool'>
(0, -1) : <class 'tuple'>
[5, 12] : <class 'list'>
{'class': 'v', 'grade': 'a'} : <class 'dict'>


In [12]:
#4)Python program to add matching keys in dictionary

x = {'a':100,'b':200,'c':300}
y = {'a':300,'b':200, 'd':400}
z = {}
k = list(y)
for key in x:
    if key in y:
        z[key] = x[key]+y[key] #add matching keys of dict x and dict y
        k.remove(key)       #remove the key from list y if its added into new dict z
    else:
        z[key] = x[key]     #if there is no match found, append it to new dict z as it is.
        for i in k:
            z[i] = y[i]
print(z)


{'a': 400, 'b': 400, 'c': 300, 'd': 400}


In [18]:
#5)Python program to replace last element of each tuple in a list with 100

L = [(10,20,30),(40,50,60),(70,80,90)]
L_new = []     #declaring empty list
for i in L:
    t = list(i)  #converting tuple into list type
    t[-1] = 100  #replacing last element of list into value 100 
    L_new.append(tuple(t))
print(L_new)
    

[(10, 20, 100), (40, 50, 100), (70, 80, 100)]


In [22]:
#6)Python program to replace letter 'r' with '$' 
# input : restart, output : resta$t

def my_fun(x):
    a = x[0]
    b = x.replace(a,'$')  #search for letter 'r' from second location as we don't want to replace first letter 'r'
    c = a+b[1:len(b)]   
    return c

print(my_fun('restart'))

resta$t


In [25]:
#7)Python program for binary search function to search value in a list

def bin_search(L,M):
    for i,j in enumerate(L):
        if j == M:
            return i,j
        else:
            if i == (len(L)-1):
                return 'NA',M
            
L = [10,20,30,40,50]
m,n = bin_search(L,50)

if m == 'NA':
    print(f'this list has no value as {n}')
else:
    print(f'the value {n} is found at position {m}')


the value 50 is found at position 4


In [62]:
#8)Python program to combine 2 lists and create a dictionary

import random
from random import shuffle
L1 = [1,2,3,4,5]
L2 = [6,7,8,9,10]
random.shuffle(L1)  #shuffle values of list l1
random.shuffle(L2)   #shuffle values of list L2
print(L1, '\n', L2)
{i:j for i,j in zip(L1,L2)}  # zipping 2 list as keys and values to a dictionary


[2, 1, 5, 3, 4] 
 [9, 6, 8, 10, 7]


{2: 9, 1: 6, 5: 8, 3: 10, 4: 7}

In [69]:
#9)Python program to find the difference between sum of 2 diagonal values
import numpy as np
def mat(a):
    b = np.asarray(a)
    c = np.trace(b)  #gives sum of diagonal
    d = np.fliplr(b)  
    e = np.trace(d)  #gives sum of another diagonal
    f = c-e
    return f
    
a = np.array([[1,2,3],[4,5,6],[7,8,20]])
print(a)
print(mat(a)) 


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 20]]
11


In [72]:
#10) Python program to find fibbonacci number using yeild

def fibn(n):
    n1 = 0
    n2 = 1
    if n == 0: 
        return 'print a valid integer'
    elif n == 1:
        return 0
    elif n == 2:
        return n1,n2
    else:
        for i in range(n):
            temp = n1+n2 #adding n1 and n2
            n1 = n2  #updating n1 with n2 value
            n2 = temp #updating n2 with temp(that's sum of last 2 numbers)

            yield(n1) #yield is generator object,it will generatw the value only when we iterate it.
            
for i in fibn(10):
    print(i)

            


1
1
2
3
5
8
13
21
34
55


In [75]:
#11)Python program to create rock paper scissor game

def rps():
    res=1
    while res==1:
        user1=input('Hi user1, Please enter your input:')
        user2=input('Hi user2, Please enter your input:')
        
        if user1=='rock'and user2=='scissor' or user1=='scissor' and user2=='paper' or user1=='paper' and user2=='rock':
            print('Congratulations! user1 has won')
        elif user1==user2:
            print('It is a tie')
        elif user2=='rock'and user1=='scissor' or user2=='scissor' and user1=='paper' or user2=='paper' and user1=='rock':
            print('Congratulations! user2 has won')
        else:
            print('Input is invalid. Please enter any one of the following: rock, scissor, paper')
        res=int(input('Do you want to play a new game? press 1 to continue: ')) 
rps()


Hi user1, Please enter your input:rock
Hi user2, Please enter your input:scissor
Congratulations! user1 has won
Do you want to play a new game? press 1 to continue: 0


In [77]:
#12)Python program to combine 2 lists of different lengths and print only common numbers in the results and there should not be any duplicates

L1 = [10,30,40,30,20,60,80,20,10]
L2 = [80,70,50,20,30,70,10]

y = list(set(L1) & set(L2)) # it will take common values from both the lists and remove duplicates if any
print(y)

[80, 10, 20, 30]


In [79]:
#13) input: mobile, expected output: eobilm
x = 'mobile'
y = x[-1]+x[1:(len(x)-1)]+x[0]
print(y)

eobilm


In [80]:
#14)Python program for password generator

import random
password=''
small='abcdefghijklmnopqrstuvwxyz'
caps='ABCDEFGHIJKLMNOPQRSTUVWXYZ'
spl='!@#$%&'
num='0123456789'
a=random.sample(small,2)
b=random.sample(caps,2)
c=random.sample(num,2)
d=random.sample(spl,2)
e=list(a+b+c+d)
random.shuffle(e)
print(''.join(e))


6dB@8%Kb


In [82]:
#15)Python program to create game of guessing a number.. 
#This game works as below. Initially program save users all favorite numbers in a list and 
# once the user pick a number in mind, program will try to guess that and says in how many attempts it has been guessed right.

import random
print('Hi user!, imagine a number. computer will guess that')
print('And computers first guess is : ')
ans = 'no'
count = 0
L = [0]
fav = [3,5,35,55,33,53]
while ans != 'yes':
    a = random.sample(fav,1)
    for i in L:
        if i == a:
            break
    else:
        L.append(a)
        print(a)
        ans = input('please say if the number is correct? ')
        count += 1
        if ans == 'no':
            pass
        else:
            print('WOW!! computer has guessed it in ',count,'attempts')


Hi user!, imagine a number. computer will guess that
And computers first guess is : 
[5]
please say if the number is correct? no
[33]
please say if the number is correct? no
[3]
please say if the number is correct? yes
wow!! computer has guessed it in  3 attempts


In [83]:
# 16) Python program to set an alaram for different days based on vacation mode

print('sun=0, mon=1, tue=2, wed=3, thu=4, fri=5, sat=6')

day=input('choose a day: ')
vacation= bool(input('enter vacation mode: '))

def fun(day,vacation):
    if day=='1' or day=='2' or day=='3' or day=='4' or day =='5':
        if vacation==0:
            print('alaram clock',(day,vacation),'-> 7:00')
        else:
            print('alaram clock',(day,vacation),'-> 10:00')
    elif day=='0' or day=='6':
        if vacation==0:
            print('alaram clock',(day,vacation),'-> 10:00')
        else:
            print('alaram clock',(day,vacation),'-> OFF')
fun(day, vacation)




sun=0, mon=1, tue=2, wed=3, thu=4, fri=5, sat=6
choose a day: 5
enter vacation mode: 1
alaram clock ('5', True) -> 10:00


In [88]:
#17)Created a birthday dictionary using python coding

bdy_dict = {'rina':'25 april','priya':'3 march','leo':'13 sep','sweeta':'16 sep','reesha':'23 dec' }
print('Welcome to bdy dictionary. we have bdy details of below:')
for i in bdy_dict:
    print(i)
name = input("Who's bdy u want to know? ")
for i in bdy_dict:
    if i == name:
        print('{} birthday is on {}'.format(name,bdy_dict[name]))
        break
else:
    print('sorry!, we dont have the details of {} '.format(name))

Welcome to bdy dictionary. we have bdy details of below:
rina
priya
leo
sweeta
reesha
Who's bdy u want to know? sweeta
sweeta birthday is on 16 sep


In [95]:
#18)Python program to find different combinations which results in sum 100

operator = ['+','-']
lines = ['1']
for i in range(2,10):
    for j in range(len(lines)):
        for op in operator:
             lines.append(lines[j]+op+str(i))
        lines[j] += str(i)

for i in lines:
    if eval(i) == 100:
        output = ('{}=100'.format(i))
        print(output)


123-45-67+89=100
123+4-5+67-89=100
12+3+4+5-6-7+89=100
12-3-4+5-6+7+89=100
1+23-4+5+6+78-9=100
1+2+3-4+5+6+78+9=100
123+45-67+8-9=100
1+2+34-5+67-8+9=100
12+3-4+5+67+8+9=100
1+23-4+56+7+8+9=100
123-4-5-6-7+8-9=100


In [98]:
#19) word frequency counter using python
#check how many times word 'is' is repeated in the given string

string = 'i was thinking statistics is easy but it is not :('
count = 0
for i in string.split():   #split function will split the string into words and store in a list format
    if i == 'is':
        count += 1
print(count)

2


In [106]:
#20)Python program to check if given ip address is valid or not?

input_ip = input('please enter ip address: ')
l = []
count = 0
for i in input_ip.split('.'):
    count += 1
    digit = i.isdigit()
    if digit == True and int(i) < 256:
        l.append(i)
    else:
        print(input_ip,'is invalid ip address')
        break
if count == 4:
    print(input_ip,'is a valid ip address') 
else:
    print(input_ip,'is invalid ip address')

please enter ip address: 255.100.1.0
255.100.1.0 is a valid ip address


In [108]:
#21)Python program to find count of digits and numbers in a given string.
# Note: space and special characters are not considered.

string =input('enter a string:')
digits=letters=0                    #initialize variables
for i in string:
    if i.isdigit():                 #if i is digit, increment digit variable by 1
        digits += 1
    elif i.isalpha():                #if i is a letter, increment letter variable by 1
            letters += 1
    else:
        pass
print("no. of digits = ", digits)
print("no. of letters =", letters)

enter a string:Hello world!!! 123
no. of digits =  3
no. of letters = 10


In [113]:
#22)Python program to calculate bank transaction
#enter input as D 400 for deposit and W 400 for withdrawal separated by comma
# example input: enter transactions: D 5000,W 2000,D 3000,W 1000

def trans_calc(s):
    sum1=0
    for i in s.split(','):
        if i[0] =='D':
            sum1 = sum1 + int(i[2:]) 
        elif i[0] == 'W':
            sum1 = sum1 - int(i[2:])
        else:
            print('wrong input')
    return sum1

input_transactions = input('enter transactions: ')
trans_calc(input_transactions)



enter transactions: D 5000,W 2000,D 3000,W 1000


5000

In [118]:
#23)Python program to create random ip address

import random
a=random.randint(0,256)  3 creating a random number between 0 255
b=random.randint(0,256)
c=random.randint(0,256)
d=random.randint(0,256)
e=list([str(a),str(b),str(c),str(d)])   
print('.'.join(e))  # displacy in a ip address format

244.118.8.44


In [120]:
#24) Rolling a dice game using python code

import random
print('Welcome to the game Roll a dice!!! ')
def dice():
    game = 1
    while game == 1:  #it will continue rolling dice untill user print say no to play again
        print('you got ')
        print(random.randint(1,7))  # generate a random number between 1 to 6
        game = int(input('do you want to roll the dice again? press 1 to continue: '))
dice()

Welcome to the game Roll a dice!!! 
you got 
3
do you want to roll the dice again? press 1 to continue: 1
you got 
5
do you want to roll the dice again? press 1 to continue: 1
you got 
3
do you want to roll the dice again? press 1 to continue: 0


In [121]:
#25) Python program to segragate values from even and odd location.
# example: input : hacker, output:hceakr

x =str(input('enter input: ')) 
y = ''
z = ''
for i,j in enumerate(x):
    if (i%2)==0:
        y=y+j
    else:
        z=z+j
output = y+z
print(output)

enter input: hacker
hceakr


In [122]:
#26) fizzbuzz game using python code
# say Fizz for multiples of 3, Buzz for multiples of 5 and FizzBuzz for multiples of both 3 and 5

for i in range(1,31):
    if (i%3)==0 and (i%5)==0:
        print('FizzBuzz')
    elif (i%3)==0:
        print('Fizz')
    elif (i%5)==0:
        print('Buzz')
    else:
        print(i)


1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz


In [124]:
#27) website blocker to block specific sites at particular timeslot
# if day is weekday and time is between 9-6, no access to particular sites. 

import webbrowser as wb
import datetime
import re

url = input('enter url: ')
websites = 'www.facebook.com, www.amazon.in, king.com, instagram.com'
day = datetime.datetime.today().weekday() #by default 0 is monday and 6 is sunday
time = datetime.datetime.now() #24 hours time format
if re.search(url, websites) and (day not in (5,7)) and (time.hour >= 9 and time.hour <= 18):
    print('Sorry!!! No access to this site from 9 am to 6 pm. :( ')
else:
    wb.open(url)
